app/routes/carteiradigital.py
from flask import Blueprint
from app.controllers.selecionar_e_cadastrar import selecionar_para_cadastrar
from app.decorator.login_required import login_required

bp = Blueprint('carteiradigital', __name__)

@bp.route('/', methods=['GET', 'POST'])
@login_required
def carteiradigital():
    return selecionar_para_cadastrar()

app/routes/logout.py
from flask import Blueprint
from app.controllers.logout import deslogar

bp = Blueprint('logout', __name__)

@bp.route('/')
def logout():
    return deslogar()

app/routes/powerBI.py
from flask import render_template, request, Blueprint
from app.controllers.bi.bi import fetch_data_situacao, quantidade_funcionarios, quantidade_funcionarios_plotly
from app.decorator.login_required import login_required


bp = Blueprint('powerBI', __name__)

@bp.route('/', methods=['GET', 'POST'])
@login_required
def powerBI():
    df_situacao = fetch_data_situacao()
    # df_identificacao_sexual = fetch_data_identificacao_sexual()
    

    filtro = request.args.get('status', '')

    # situacao_funcionario = situacao()
    # identificacao_sexual_funcionario = identificacao_sexual()
    qtd_funcionarios = quantidade_funcionarios().to_dict(orient='records')

    total_funcionarios = sum(row['quantidade'] for row in qtd_funcionarios)
    qtd_funcionarios.append({'status': 'Total', 'quantidade': total_funcionarios})
    
    if filtro and filtro != 'Todos':
        df_situacao = df_situacao[df_situacao['status'] == filtro]


    # return render_template(
    #                        'bi.html', tabela = df_situacao.to_dict(orient='records'), 
    #                        situacao_funcionario = situacao_funcionario, 
    #                     #    identificacao_sexual_funcionario = identificacao_sexual_funcionario, 
    #                        filtro = filtro,
    #                        qtd_funcionarios=qtd_funcionarios
    #                     )

    grafico_situacao = quantidade_funcionarios_plotly()
    return render_template(  'bi.html',
                           grafico_situacao=grafico_situacao, 
                           filtro=filtro, qtd_funcionarios=qtd_funcionarios, 
                           tabela=df_situacao.to_dict(orient='records')
                           )

app/templates/includes/favicon.jinja2
<link rel="shortcut icon" href="{{ url_for('static', filename='assets/rh.png') }}" type="image/x-icon">

app/templates/includes/footer.jinja2
 <footer>
    Pode colocar o que você quiser aqui
    <div class="user">
      <p>
        <b>Usuário:</b> {{session['user']}} 
        <br>
        <b>E-mail:</b> {{session['email']}}
      </p>
      <a href="{{ url_for('logout.logout') }}" class="sair">Sair</a>
    </div>
    
  </footer>

app/templates/includes/menu.jinja2
  <div class="menu">
    <a href="/"><button>Adicionar funcionário</button></a>
    <!-- <a href="./alterar"><button>Alterar dados do funcionário</button></a> -->
    <a href="{{ url_for('selecionarDadosCadastrais.selecionarDadosCadastrais') }}"><button>Selecionar funcionário</button></a> 
    <a href="{{ url_for('carteiradigital.carteiradigital') }}"><button>Cadastrar carteira digital</button></a> 
    <!--<a href="{{ url_for('powerBI.powerBI') }}"><button>Power BI</button></a> -->
  </div>