app/models/esqueci_senha.py
from flask import *
from app.models.banco import *
from app.extensions.bcrypt import bcrypt

def mudar_senha():   
    try:
        conexao = connection()
        cursor = conexao.cursor(dictionary=True)
        
        if request.method == 'POST':
            email = request.form['email']
            username = request.form['username']
            password = request.form['password']
            confirm_password = request.form['confirm_password']
            cpf = request.form['cpf']
            

            cursor.execute("SELECT * FROM usuario WHERE email = %s AND username = %s ", (email, username))
            usuario_existente = cursor.fetchone()

            

            if usuario_existente:
                hashed_cpf = bcrypt.check_password_hash(usuario_existente['cpf'], cpf)
                if not hashed_cpf:
                    current_app.logger.info(f"Usuario {username}, E-mail {email}, teve tentativa inválida de troca de senha.")
                    flash('Credenciais inválidas. Tente novamente.', 'erro')

                elif password != confirm_password:
                    flash('As senhas não coincidem!', 'erro')
                    current_app.logger.info(f"Usuario {username}, E-mail {email}, teve tentativa inválida de troca de senha.")
                    
                else:
                    hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
                    
                    query = "UPDATE usuario SET password = %s WHERE username = %s AND email = %s"
                    valores = (hashed_password, username, email)
                    cursor.execute(query, valores)

                    current_app.logger.info(f"Usuario {username}, E-mail {email}, teve sua senha alterado com sucesso.")
                    conexao.commit()
                    flash('Senha alterada com sucesso.', 'sucesso')
                    return redirect(url_for('esqueci_senha.esqueci_senha'))
            else:
                current_app.logger.info(f"Usuario {username}, E-mail {email}, teve tentativa inválida de troca de senha.")
                flash('Credenciais inválidas. Tente novamente.', 'erro')
                return render_template('esqueci_senha.html')
            
    except Exception as e: 
        current_app.logger.error(f"Erro ao trocar senha: {str(e)}")
        flash(f'Erro: {str(e)}', 'erro')
        return render_template('esqueci_senha.html')
    
    finally:
        cursor.close()
        conexao.close()
          
    return render_template('esqueci_senha.html')

app/models/login.py
from app.models.banco import *
from flask import *
from app.models.autenticar_user import autenticar_usuario


def logar():
    if request.method == 'POST':
        email = request.form['email']
        username = request.form['username']
        password = request.form['password']

        user = autenticar_usuario(email,username, password)
        if user:
            session['user'] = user['username']  # Salva o usuário na sessão
            session['email']= user['email']
            current_app.logger.info(f"Usuario {username}, E-mail {email} logado com sucesso.")
            flash(f'Login realizado com sucesso. Bem-vindo {username}', 'sucesso')
            return redirect(url_for('index.index'))
        else:
            current_app.logger.warning(f"Tentativa de login falhada para o usuario {username}.")
            flash('Credenciais inválidas. Tente novamente.', 'erro')

    return render_template('login.html')

app/models/registrar_usuario.py
from flask import *
from app.models.cadastrar_usuario import cadastrar_usuario

def registrar_usuario():
    if request.method == 'POST':
        email = request.form['email']
        username = request.form['username']
        password = request.form['password']
        confirm_password = request.form['confirm_password']
        cpf = request.form['cpf']


        if password != confirm_password:
            flash('As senhas não coincidem!', 'erro')
        else:
            sucesso = cadastrar_usuario(email, username, password, cpf)
            if sucesso:
                return redirect(url_for('login.login'))
            else:
                return render_template('registrarUsuario.html', email=email, username=username)

    return render_template('registrarUsuario.html')

app/controllers/esqueci_senha.py
from flask import request, render_template, flash, redirect, url_for, current_app
from app.controllers.banco import connection
from app.extensions.bcrypt import bcrypt

def mudar_senha():   
    try:
        conexao = connection()
        cursor = conexao.cursor(dictionary=True)
        
        if request.method == 'POST':
            email = request.form['email']
            username = request.form['username']
            password = request.form['password']
            confirm_password = request.form['confirm_password']
            cpf = request.form['cpf']
            

            cursor.execute("SELECT * FROM usuario WHERE email = %s AND username = %s ", (email, username))
            usuario_existente = cursor.fetchone()

            

            if usuario_existente:
                hashed_cpf = bcrypt.check_password_hash(usuario_existente['cpf'], cpf)
                if not hashed_cpf:
                    current_app.logger.info(f"Usuario {username}, E-mail {email}, teve tentativa inválida de troca de senha.")
                    flash('Credenciais inválidas. Tente novamente.', 'erro')

                elif password != confirm_password:
                    flash('As senhas não coincidem!', 'erro')
                    current_app.logger.info(f"Usuario {username}, E-mail {email}, teve tentativa inválida de troca de senha.")
                    
                else:
                    hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
                    
                    query = "UPDATE usuario SET password = %s WHERE username = %s AND email = %s"
                    valores = (hashed_password, username, email)
                    cursor.execute(query, valores)

                    current_app.logger.info(f"Usuario {username}, E-mail {email}, teve sua senha alterado com sucesso.")
                    conexao.commit()
                    flash('Senha alterada com sucesso.', 'sucesso')
                    return redirect(url_for('esqueci_senha.esqueci_senha'))
            else:
                current_app.logger.info(f"Usuario {username}, E-mail {email}, teve tentativa inválida de troca de senha.")
                flash('Credenciais inválidas. Tente novamente.', 'erro')
                return render_template('esqueci_senha.html')
            
    except Exception as e: 
        current_app.logger.error(f"Erro ao trocar senha: {str(e)}")
        flash(f'Erro: {str(e)}', 'erro')
        return render_template('esqueci_senha.html')
    
    finally:
        cursor.close()
        conexao.close()
          
    return render_template('esqueci_senha.html')

app/controllers/login.py
# from app.controllers.banco import *
from flask import render_template, request, redirect, url_for, session, flash, current_app
from app.controllers.autenticar_user import autenticar_usuario
from app.controllers.auditoria.usuario_logado.usuario_logado import auditoria_banco_login

def logar():
    if request.method == 'POST':
        email = request.form['email']
        username = request.form['username']
        password = request.form['password']

        user = autenticar_usuario(email,username, password)
        if user:
            session['user'] = user['username']  # Salva o usuário na sessão
            session['email']= user['email']
            current_app.logger.info(f"Usuario {username}, E-mail {email} logado com sucesso.")

            auditoria_banco_login(email, username)

            flash(f'Login realizado com sucesso. Bem-vindo {username}', 'sucesso')
            return redirect(url_for('index.index'))
        else:
            current_app.logger.warning(f"Tentativa de login falhada para o usuario {username}.")
            flash('Credenciais inválidas. Tente novamente.', 'erro')

    return render_template('login.html')

app/controllers/registrar_usuario.py
from flask import request, render_template, redirect, url_for, flash
from app.controllers.cadastrar_usuario import cadastrar_usuario

def registrar_usuario():
    if request.method == 'POST':
        email = request.form['email']
        username = request.form['username']
        password = request.form['password']
        confirm_password = request.form['confirm_password']
        cpf = request.form['cpf']


        if password != confirm_password:
            flash('As senhas não coincidem!', 'erro')
        else:
            sucesso = cadastrar_usuario(email, username, password, cpf)
            if sucesso:
                return redirect(url_for('login.login'))
            else:
                return render_template('registrarUsuario.html', email=email, username=username)

    return render_template('registrarUsuario.html')

app/routes/cadastroDeFuncionario.py
from flask import Blueprint
from app.decorator.login_required import login_required
from app.controllers.cadastro_funcionario import cadastro_funcinarios

bp = Blueprint('cadastroDeFuncionario', __name__)

@bp.route('/', methods=['GET', 'POST'])
@login_required
def cadastroDeFuncionario():
    return cadastro_funcinarios()

app/routes/carteiradigital.py
from flask import Blueprint
from app.controllers.selecionar_e_cadastrar import selecionar_para_cadastrar
from app.decorator.login_required import login_required

bp = Blueprint('carteiradigital', __name__)

@bp.route('/', methods=['GET', 'POST'])
@login_required
def carteiradigital():
    return selecionar_para_cadastrar()

app/routes/esqueci_senha.py
from flask import Blueprint
from app.controllers.esqueci_senha import mudar_senha

bp = Blueprint('esqueci_senha', __name__)

@bp.route('/', methods=['GET','POST'])
def esqueci_senha():
    return mudar_senha()

app/routes/login.py
from flask import Blueprint
from app.controllers.login import logar

bp = Blueprint('login', __name__)

@bp.route('/', methods=['GET', 'POST'])
def login():
    return logar()

app/routes/powerBI.py
from flask import render_template, request, Blueprint
from app.controllers.bi.bi import fetch_data_situacao, quantidade_funcionarios, quantidade_funcionarios_plotly
from app.decorator.login_required import login_required


bp = Blueprint('powerBI', __name__)

@bp.route('/', methods=['GET', 'POST'])
@login_required
def powerBI():
    df_situacao = fetch_data_situacao()
    # df_identificacao_sexual = fetch_data_identificacao_sexual()
    

    filtro = request.args.get('status', '')

    # situacao_funcionario = situacao()
    # identificacao_sexual_funcionario = identificacao_sexual()
    qtd_funcionarios = quantidade_funcionarios().to_dict(orient='records')

    total_funcionarios = sum(row['quantidade'] for row in qtd_funcionarios)
    qtd_funcionarios.append({'status': 'Total', 'quantidade': total_funcionarios})
    
    if filtro and filtro != 'Todos':
        df_situacao = df_situacao[df_situacao['status'] == filtro]


    # return render_template(
    #                        'bi.html', tabela = df_situacao.to_dict(orient='records'), 
    #                        situacao_funcionario = situacao_funcionario, 
    #                     #    identificacao_sexual_funcionario = identificacao_sexual_funcionario, 
    #                        filtro = filtro,
    #                        qtd_funcionarios=qtd_funcionarios
    #                     )

    grafico_situacao = quantidade_funcionarios_plotly()
    return render_template(  'bi.html',
                           grafico_situacao=grafico_situacao, 
                           filtro=filtro, qtd_funcionarios=qtd_funcionarios, 
                           tabela=df_situacao.to_dict(orient='records')
                           )

app/routes/registrarUsuario.py
from flask import Blueprint
from app.controllers.registrar_usuario import registrar_usuario

bp = Blueprint('registrarUsuario', __name__)

@bp.route('/', methods=['GET', 'POST'])
def registrarUsuario():
    return registrar_usuario()

app/templates/bi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/bi.css">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    {% include 'includes/favicon.jinja2' %}    
    <title>PowerBI</title>
</head>
<body>
    {% include 'includes/menu.jinja2' %}

    <!-- <div class="graficos">
        <div class="grafico_situacao">
            <h1>Situaçãos</h1>
            <img src="{{ url_for('static', filename='imgBI/situacao.png') }}" alt="Gráfico de Pizza">
        </div>
        
        <div class="grafico_identificacao_sexual">
            <h1>Identificação Sexual</h1 >
            <img src="{{ url_for('static', filename='imgBI/identificacao.png') }}" alt="Gráfico de Identificação Sexual">
        </div> 
    </div> -->

    <h1>Situaçãos dos funcionários</h1>
    <div>{{ grafico_situacao | safe }}</div>

    <div class="resumo">

        <h2>Resumo de Funcionários</h2>
        <table class="tabResumo" border="1">
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Quantidade de funcionários</th>
                </tr>
            </thead>
            <tbody>
                {% for row in qtd_funcionarios %}
                <tr>
                    <td>{{ row['status'] }}</td>
                    <td>{{ row['quantidade'] }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>

        
    <h2>Tabela de Funcionários</h2>
    <form method="get" action="{{ url_for('powerBI.powerBI') }}">
        <label for="status">Status:</label>
        <select id="status" name="status" required>
            <option value="">Selecione o Status</option>
            <option value="Todos" {% if filtro == 'Todos' %}selected{% endif %}>Todos</option>
            <option value="Ativo" {% if filtro == 'Ativo' %}selected{% endif %}>Ativo</option>
            <option value="Inativo" {% if filtro == 'Inativo' %}selected{% endif %}>Inativo</option>
            <option value="Desligado" {% if filtro == 'Desligado' %}selected{% endif %}>Desligado</option>
        </select>
        <button type="submit">Filtrar</button>
    </form>
        



    <table border="1">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Matrícula</th>
                <th>Situação</th>
                <th>Contratação</th>
            </tr>
        </thead>
        <tbody>
            {% for row in tabela %}
            <tr>
                <td>{{ row['nome'] }}</td>
                <td>{{ row['matricula'] }}</td>
                <td>{{ row['status'] }}</td>
                <td>{{ row['contratacao'] }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

app/templates/carteira.html
{% from "macros/macros.jinja2" import validacao %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cadastro de carteirinha</title>
  <link rel="stylesheet" href="../static/css/carteira.css">
  {% include 'includes/favicon.jinja2' %}
</head>
<body>
  {% include 'includes/menu.jinja2' %}

    <div class="titulo">
      <h2>CADASTRO DE CARTEIRA DIGITAL</h2> 
      <div class="interrogacao"><img src="../static/assets/interrogacao.png" alt=""></div> 
      <div class="overlay" id="overlay"></div>
      <div class="info-box" id="infoBox">
        <p>Digite a matrícula do funcionário, os dados aparecerão nos campos abaixo.</p><br>
        <p>Apenas é permitido inserir informações dos campos com as bordas avermelhadas.</p><br>
        <ul>
          <li>Foto do funcionário</li>
          <li>Assinatura do funcionário</li>
          <li>Status do funcionário.</li>
        </ul>
        <button id="closeButton">Fechar</button>
      </div>
    </div>
    
    <div class="container">
  
      
      {{ validacao() }}
  
      <!-- Formulário para buscar funcionário -->
      <form class="form-container" method="POST" action="{{ url_for('carteiradigital.carteiradigital') }}" enctype="multipart/form-data">
        <div class="form">
          <label for="matricula">Matrícula:</label>
          <input type="text" id="matricula" name="matricula" placeholder="Digite a matrícula" required oninput="mascaraMatricula(this)" minlength="9" maxlength="9" value="{{ pessoa.matricula if pessoa else '' }}">
  
          <button id="selectFuncionario" type="submit"><b>SELECIONAR FUNCIONÁRIO</b></button>
        </div>
      </form>
  
      <!-- Formulário para envio de fotos e assinatura -->
      <form class="form-container" method="POST" action="{{ url_for('carteiradigital.carteiradigital') }}" enctype="multipart/form-data">
        <div class="form">
          
          <label for="status">Status:</label>
          <select id="status" name="status" required>
            <option value="">Selecione o Status</option>
            <option value="ATIVO">ATIVO</option>
            <option value="SUSPENSO">SUSPENSO</option>
            <option value="BLOQUEADO">BLOQUEADO</option>
          </select>

          <label for="name">Nome:</label>
          <input type="text" id="name" name="nome" placeholder="Nome do funcionário" readonly value="{{ pessoa.NOME if pessoa else '' }}">
  
          <label for="matricula">Matrícula:</label>
          <input type="text" id="matricula" name="matricula" placeholder="Matrícula do funcionário" readonly required value="{{ pessoa.MATRICULA if pessoa else '' }}">

          <label for="cpf">CPF:</label>
          <input type="text" id="cpf" name="cpf" placeholder="CPF do funcionário" readonly value="{{ pessoa.CPF if pessoa else '' }}">
  
          <label for="nascimento">Data de nascimento:</label>
          <input type="date" id="nascimento" name="nascimento" readonly value="{{ pessoa.DATA_NASCIMENTO if pessoa else '' }}">

          <label for="cargo">Cargo:</label>
          <input type="text" id="cargo" name="cargo" placeholder="Cargo do funcionário" readonly value="{{ pessoa.CARGO if pessoa else '' }}">

          <label for="mae">Nome da Mãe:</label>
          <input type="text" id="mae" name="mae" placeholder="Nome da mãe do funcionário" readonly value="{{ pessoa.MAE if pessoa else '' }}">

          <label for="pai">Nome do Pai:</label>
          <input type="text" id="pai" name="pai" placeholder="Nome do pai do funcionário" readonly value="{{ pessoa.PAI if pessoa else '' }}">

          <label for="nacionalidade">Nacionalidade:</label>
          <input type="text" id="nacionalidade" name="nacionalidade" placeholder="Nacionalidade do funcionário" readonly value="{{ pessoa.NACIONALIDADE if pessoa else '' }}">
          
        
          <button id="cadastrarCarteirinha" type="submit"><b>CADASTRAR CARTEIRA DIGITAL</b></button>
        </div>
  
        <div class="photo-section">
          <div class="photo-container">
            <label for="foto"><b>Foto do funcionário:</b></label>
            <input type="file" id="foto" name="foto" accept="image/*" onchange="previewImage(event, 'imgFoto')" required>
            <img id="imgFoto" src="{{ pessoa.foto if pessoa and pessoa.foto else url_for('static', filename='assets/foto.png') }}" alt="Foto do funcionário" >
          </div>
  
          <div class="photo-container">
            <label for="assinatura"><b>Assinatura do funcionário:</b></label>
            <input type="file" id="assinatura" name="assinatura" accept="image/*" onchange="previewImage(event, 'imgAssinatura')" required>
            <img id="imgAssinatura" src="{{ pessoa.assinatura if pessoa and pessoa.assinatura else url_for('static', filename='assets/assinatura.png') }}" alt="Assinatura do funcionário">
          </div>
          
        </div>
  
      </form>
      
    </div>
  
    {% include 'includes/footer.jinja2' %}
  
    <script src="../static/scripts/matricula.js"></script>
  </body>
  </html>

app/templates/index.html
{% from "macros/macros.jinja2" import validacao %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cadastro Funcionário</title>
  <link rel="stylesheet" href="../static/css/style.css">
  {% include 'includes/favicon.jinja2' %}
</head>
<body>
  {% include 'includes/menu.jinja2' %}

  <div class="titulo">
    <h2>CADASTRO DE FUNCIONÁRIO</h2> 
    <div class="interrogacao"><img src="../static/assets/interrogacao.png" alt=""></div> 
    <div class="overlay" id="overlay"></div>
    <div class="info-box" id="infoBox">
      <p>Cadastre os dados do novo funcionário.</p><br>
      <p>As informações cadastradas serão salvas no banco de dados.</p><br>
      <button id="closeButton">Fechar</button>
    </div>
  </div>

  <div class="container">
    {{ validacao() }}

    <form class="form-container" method="POST" action="{{ url_for('cadastroDeFuncionario.cadastroDeFuncionario') }}" enctype="multipart/form-data">
      <div class="form">
        <label for="name">Nome:</label>
        <input type="text" id="name" name="nome" placeholder="Digite o nome" required>

        <label for="matricula">Matrícula:</label>
        <input type="text" id="matricula" name="matricula" placeholder="Digite a matrícula" oninput="mascaraMatricula(this)" minlength="9" maxlength="9" required>

        <label for="contratacao">CPF:</label>
        <input type="text" id="cpf" name="cpf" oninput="mascaraCPF(this)" minlength="14" maxlength="14" placeholder="Digite o cpf" required>

        <label for="nascimento">Data de nascimento:</label>
        <input type="date" id="nascimento" name="nascimento" required>

        <label for="cargo">Cargo:</label>
        <select id="cargo" name="cargo" required>
          <option value="">SELECIONE O CARGO DO FUNCIONÁRIO</option>
          <option value="AGENTE DE ADMINISTRAÇÃO">AGENTE DE ADMINISTRAÇÃO</option>
          <option value="AGENTE DE PORTARIA DA PROCURADORIA">AGENTE DE PORTARIA DA PROCURADORIA</option>
          <option value="AGENTE EDUCADOR II">AGENTE EDUCADOR II</option>
          <option value="ANALISTA DE PROCURADORIA">ANALISTA DE PROCURADORIA</option>
          <option value="ARQUITETO">ARQUITETO</option>
          <option value="ARQUITETO DE PROCURADORIA">ARQUITETO DE PROCURADORIA</option>
          <option value="ASSISTENTE DE DOCUMENTAÇÃO">ASSISTENTE DE DOCUMENTAÇÃO</option>
          <option value="CARGO EM COMISSÃO">CARGO EM COMISSÃO</option>
          <option value="CONTADOR DA PROCURADORIA">CONTADOR DA PROCURADORIA</option>
          <option value="ENGENHEIRO CIVIL">ENGENHEIRO CIVIL</option>
          <option value="ENGENHEIRO DA PROCURADORIA">ENGENHEIRO DA PROCURADORIA</option>
          <option value="ESTAGIÁRIO DE ADMINISTRAÇÃO">ESTAGIÁRIO DE ADMINISTRAÇÃO</option>
          <option value="ESTAGIÁRIO DE ARQUITETURA">ESTAGIÁRIO DE ARQUITETURA</option>
          <option value="ESTAGIÁRIO DE BIBLIOTECONOMIA">ESTAGIÁRIO DE BIBLIOTECONOMIA</option>
          <option value="ESTAGIÁRIO DE CONTABILIDADE">ESTAGIÁRIO DE CONTABILIDADE</option>
          <option value="ESTAGIÁRIO DE DESIGNER GRÁFICO">ESTAGIÁRIO DE DESIGNER GRÁFICO</option>
          <option value="ESTAGIÁRIO DE DIREITO PGM">ESTAGIÁRIO DE DIREITO PGM</option>
          <option value="ESTAGIÁRIO DE ENGENHARIA CIVIL">ESTAGIÁRIO DE ENGENHARIA CIVIL</option>
          <option value="ESTAGIÁRIO DE INFORMÁTICA">ESTAGIÁRIO DE INFORMÁTICA</option>
          <option value="MOTORISTA">MOTORISTA</option>
          <option value="PROCURADOR DO MUNICÍPIO">PROCURADOR DO MUNICÍPIO</option>
          <option value="PROFESSOR II">PROFESSOR II</option>
          <option value="PROFISSIONAL DE NÍVEL MÉDIO">PROFISSIONAL DE NÍVEL MÉDIO</option>
          <option value="RESIDENTE JURÍDICO">RESIDENTE JURÍDICO</option>
          <option value="SECRETÁRIO ESCOLAR">SECRETÁRIO ESCOLAR</option>
          <option value="SERVENTE">SERVENTE</option>
          <option value="SERVENTE DA PROCURADORIA">SERVENTE DA PROCURADORIA</option>
          <option value="TÉCNICO DE CONTROLE INTERNO">TÉCNICO DE CONTROLE INTERNO</option>
          <option value="TÉCNICO DE PRODUÇÃO E ORGANIZAÇÃO">TÉCNICO DE PRODUÇÃO E ORGANIZAÇÃO</option>
          <option value="TELEFONISTA DA PROCURADORIA">TELEFONISTA DA PROCURADORIA</option>
        </select>

       
        <label for="frase_estagiario" id="est">Estagiário?

          <input type="checkbox" id="frase_estagiario" name="frase_estagiario" value="O portador está credenciado para estagiar na Procuradoria Geral do Município do Rio de Janeiro nos termos da Lei Federal nº 11.788, de 25/09/2008, e suas alterações.">
            <br>
          APENAS ESTAGIÁRIOS!
        </label>
     

        <label for="mae">Nome da Mãe:</label>
        <input type="text" id="mae" name="mae" placeholder="Digite o nome da mãe" required>

        <label for="pai">Nome do Pai:</label>
        <input type="text" id="pai" name="pai" placeholder="Digite o nome do pai">
        
        <label for="nacionalidade">Nacionalidade:</label>
        <input type="text" id="nacionalidade" name="nacionalidade" placeholder="Digite a nacionalidade" required>

        <label for="status">Status:</label>
        <select id="status" name="status" required>
          <option value="">Selecione o Status</option>
          <option value="ATIVO">ATIVO</option>
          <option value="SUSPENSO">SUSPENSO</option>
          <option value="BLOQUEADO">BLOQUEADO</option>
        </select>

        

        <button id="cadastrarFuncionario" type="submit"><b>CADASTRAR FUNCIONÁRIO</b></button>
      </div>

      <div class="photo-section">
        <div class="photo-container">
          <label for="foto"><b>Foto do funcionário:</b></label>
          <input type="file" id="foto" name="foto" accept="image/*" required onchange="previewImage(event, 'imgFoto')" >
          <img id="imgFoto" src="{{ pessoa.foto if pessoa and pessoa.foto else url_for('static', filename='assets/foto.png') }}" alt="Foto do funcionário" >
        </div>

        <div class="photo-container">
          <label for="assinatura"><b>Assinatura do funcionário:</b></label>
          <input type="file" id="assinatura" name="assinatura" accept="image/*" required onchange="previewImage(event, 'imgAssinatura')" >
          <img id="imgAssinatura" src="{{ pessoa.assinatura if pessoa and pessoa.assinatura else url_for('static', filename='assets/assinatura.png') }}">
        </div>
      </div>
    </form>
    <br>
    
  </div>

  {% include 'includes/footer.jinja2' %}

  <script src="../static/scripts/matriculaEcpf.js"></script>
</body>
</html>

app/templates/login.html
{% from "macros/macros.jinja2" import login %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    {% include 'includes/favicon.jinja2' %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">



</head>
<body>
    <div class="container">
        <h1>Login</h1>
        
        {{ login() }}

        
        <form method="POST" action="{{ url_for('login.login') }}">
            <div class="form-group">
                <label for="email">E-mail</label>
                <input type="email" id="email" name="email" class="form-control" placeholder="Digite seu e-mail" required>
            </div>
            <div class="form-group">
                <label for="username">Usuário</label>
                <input type="text" id="username" name="username" class="form-control" placeholder="Digite seu nome de usuário" minlength="6" maxlength="20" required>
            </div>
            <div class="form-group">
                <label for="password">Senha</label>
                <!-- <input type="password" id="password" name="password" class="form-control" placeholder="Digite sua senha" minlength="6" maxlength="12" required> -->
                <div class="password-wrapper">
                    <input type="password" id="password" name="password" class="form-control" placeholder="Digite sua senha" maxlength="12" required>
                    <span class="toggle-password" onclick="togglePasswordVisibility('password', this)">
                        <i class="fas fa-eye"></i>
                    </span>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Entrar</button>
            <br><br>
            
        </form>
        <div class="cadastrarOuTrocarSenha">
            <a href="/registrarUsuario"><button type="submit" class="cadastrar-usuario">Cadastrar usuário</button></a>
            <a href="/esqueci_senha"><button type="submit" class="cadastrar-usuario">Esqueci minha senha</button></a>
        </div>
    </div>

    <footer>Pode colocar o que você quiser aqui</footer>

    <script src="../static/scripts/scripts.js"></script>

</body>
</html>